### ISSUE TITLE
Miyoo Mini stuck on black screen

### ISSUE THREAD

**Issue by lulasz** [zbtnot/hello-miyoo#1]
Hey! I couldn't find any other way to contact you. I just got my Miyoo Mini Plus and compiled your project using the toolchain, but when I put it into the Ports folder as standalone. It just stays at black screen.

Could you explain how did you achieve to get it running on the console? I would like to port my game using SDL (1.2 is fine) and your "Template" looks great as starting point.

**Comment by zbtnot** [comment]
Hi there! I haven't used the Ports folder so I'm not sure what if any special work needs to be done to account for those. Launching the produced executable should work from the OnionOS file explorer (DinguxCommander) though. 

Perhaps that does something special to enable the application to take control that Ports doesn't? I'd love to know the answer.

**Comment by lulasz** [comment]
Alright, my config file for the port was wrong. I have attached it as zip, since I will use your repo as my starting point and want to thank :) 
[Roms.zip](https://github.com/zbtnot/hello-miyoo/files/12372942/Roms.zip)

**Comment by zbtnot** [comment]
Very cool! I'll have to play with this more 💯
